var C = module.exports = {}
C.annoservicehosturl = process.env.annoservicehosturl || 'http://anno.ub.uni-heidelberg.de'
C.annoserviceurl     = process.env.annoserviceurl     || C.annoservicehosturl + '/cgi-bin/anno.cgi';
C.typeList = {
    "dc:description-ger":   "text",
    "dc:identifier":        "identifier",
    "dc:title":             "title",
    "foaf:account":         "account",
    "foaf:name":            "user_name",
    "jcr:lastModified":     "jcr_modified",
    "jcr:uuid":             "uuid",
    "dc:source":            "link",
    "dc:sourceDescription": "sourcedescription",
    "jcr:versionHistory":   "versioned",
    "dc:type":              "type",
    "svg:polygon":          'svg_polygon',
    "user_rights":          'user_rights'
};
C.fields = {
  'id':        'clean_svname',
  'title':     'title',
  'text':      'test',
  'link':      'link',
  'linktitle': 'sourcedescription',
  'polygon':   'svg_polygon',
};
C.texts = [
    'headline',
    'login',
    'new',
    'open_all',
    'close',
    'close_all',
    'sort',
    'edit',
    'comment',
    'commenttarget',
    'reply',
    'comments',
    'previous',
    'sortdate',
    'sortdatereverse',
    'sorttitle',
    'purl',
    'save',
    'cancel',
    'edit_headline',
    'annofield_title',
    'annofield_link',
    'annofield_linktitle',
    'license',
    'version_from',
    'showref',
    'showrefdefault',
    'showrefnever',
    'showrefalways',
    'metadata',
    'zones',
    'edit_zones'
]

C.localizations = {
    'de':                      {
        'headline':            'Annotationen',
        'login':               'Anmelden',
        'new':                 'Neue Annotation',
        'open_all':            'Alle öffnen',
        'close':               'Schließen',
        'close_all':           'Alle schließen',
        'sort':                'Sortieren',
        'edit':                'Editieren',
        'comment':             'Kommentieren',
        'commenttarget':       'Kommentar zu',
        'reply':               'Antworten',
        'comments':            'Kommentare',
        'previous':            'Vorherige Version',
        'sortdate':            'Chronologisch aufsteigend',
        'sortdatereverse':     'Chronologisch absteigend',
        'sorttitle':           'Titel aufsteigend',
        'save':                'Speichern',
        'cancel':              'Abbrechen',
        'edit_headline':       'Annotationen-Editor',
        'annofield_title':     'Titel (Pflichtfeld)',
        'annofield_link':      'Link (URL)',
        'annofield_linktitle': 'Link-Titel',
        'license':             'Annotation wird unter CC0-Lizenz (Public Domain) veröffentlicht.',
        'version_from':        'Version vom',
        'showref':             'Bildbezüge anzeigen',
        'showrefdefault':      'Standard',
        'showrefnever':        'Nie',
        'showrefalways':       'Immer',
        'metadata':            'Metadaten',
        'zones':               'Zonen',
        'purl':                'Annotation: Persistente URL',
        'edit_zones':          'Zonen editieren',
    },
    'en':                      {
        'Annotationen':        'Annotations',
        'Anmelden':            'Login',
        'Neue Annotation':     'New annotation',
        'open_all':            'Open all',
        'close':               'Close',
        'close_all':           'Close all',
        'sort':                'Sort',
        'edit':                'Edit',
        'comment':             'Comment',
        'commenttarget':       'Comment on',
        'reply':               'Reply',
        'comments':            'Comments',
        'previous':            'Previous versions',
        'sortdate':            'by time (ascending)',
        'sortdatereverse':     'by time (descending)',
        'sorttitle':           'by title',
        'save':                'Save',
        'cancel':              'Cancel',
        'edit_headline':       'Annotation Editor',
        'annofield_title':     'Title (required)',
        'annofield_link':      'Link (URL)',
        'annofield_linktitle': 'Link title',
        'license':             'Annotation is published under CC0 license (Public Domain)',
        'license_comment':     'Comment is published under CC0 license (Public Domain)',
        'version_from':        'Version vom',
        'showref':             'Bildbezüge anzeigen',
        'showrefdefault':      'mouseover',
        'showrefnever':        'never',
        'showrefalways':       'always',
        'metadata':            'Metadata',
        'zones':               'Zones',
        'purl':                'Annotation: Persistent URL',
        'edit_zones':          'Edit zones',
    }
};

C.langcode = {
   'en':  'en',
   'eng': 'en',
   'de':  'de',
   'ger': 'de',
};

C.defaultlang = 'de';
