var C = module.exports = {}

C.defaultlang = 'de';

C.localizations = {
    'de':                      {
        'annofield_link':      'Link (URL)',
        'annofield_linktitle': 'Link-Titel',
        'annofield_title':     'Titel (Pflichtfeld)',
        'cancel':              'Abbrechen',
        'close':               'Schließen',
        'close_all':           'Alle schließen',
        'comment':             'Kommentieren',
        'comments':            'Kommentare',
        'commenttarget':       'Kommentar zu',
        'edit':                'Editieren',
        'edit_headline':       'Annotationen-Editor',
        'edit_zones':          'Zonen editieren',
        'Annotations':         'Annotationen',
        'license':             'Annotation wird unter CC0-Lizenz (Public Domain) veröffentlicht.',
        'login':               'Anmelden',
        'logout':              'Abmelden',
        'metadata':            'Metadaten',
        'new':                 'Neue Annotation',
        'no_annotations_yet':  'Noch keine Annotationen',
        'open_all':            'Alle öffnen',
        'previous':            'Vorherige Version',
        'purl':                'Annotation: Persistente URL',
        'reply':               'Antworten',
        'save':                'Speichern',
        'showref':             'Bildbez\u00fcge anzeigen',
        'showrefalways':       'Immer',
        'showrefdefault':      'Standard',
        'showrefnever':        'Nie',
        'sort':                'Sortieren',
        'sortdate':            'Chronologisch aufsteigend',
        'sortdatereverse':     'Chronologisch absteigend',
        'sorttitle':           'Titel aufsteigend',
        'version_from':        'Version vom',
        'zones':               'Zonen',

        'add_semtag':          'Semantisches Schlagwort hinzuf\u00fcgen',
        'add_tag':             'Einfaches Schlagwort hinzuf\u00fcgen',
        'delete_semtag':       'Semantisches Tag l\u00f6schen',
        'delete_tag':          'Einfaches Tag l\u00f6schen',
        'semtag':              'Semantisches Schlagwort',
        'semtags':             'Semantische Schlagworte',
        'tag':                 'Einfaches Schlagwort',
        'tags':                'Einfache Schlagworte',

        'delete_anno':         'L\u00f6schen',
        'confirm_delete':      'Sind sie sicher dass Sie die Annotation l\u00f6schen wollen?',

        'unsaved':             'Nicht gespeichert',
        'discard':             'Verwerfen',
        'annoeditor':          'Annotations-Editor',

        "preview":             'Vorschau',

        "fmt_bold":        "Fett",
        "fmt_size":        "Schriftgr\u00f6\u00dfe",
        "fmt_size_small":  "Klein",
        "fmt_size_normal": "Normal",
        "fmt_size_large":  "Gro\u00df",
        "fmt_size_huge":   "Riesig",

    },
    'en':                      {
        'annofield_link':      'Link (URL)',
        'annofield_linktitle': 'Link title',
        'annofield_title':     'Title (required)',
        'cancel':              'Cancel',
        'close':               'Close',
        'close_all':           'Close all',
        'comment':             'Comment',
        'comments':            'Comments',
        'commenttarget':       'Comment on',
        'edit':                'Edit',
        'edit_headline':       'Annotation Editor',
        'edit_zones':          'Edit zones',
        'login':               'Log in',
        'logout':              'Log out',
        'license':             'Annotation is published under CC0 license (Public Domain)',
        'license_comment':     'Comment is published under CC0 license (Public Domain)',
        'metadata':            'Metadata',
        'new':                 'New Annotation',
        'no_annotations_yet':  'No Annotations yet',
        'open_all':            'Open all',
        'previous':            'Previous versions',
        'purl':                'Annotation: Persistent URL',
        'reply':               'Reply',
        'save':                'Save',
        'showref':             'Bildbezüge anzeigen',
        'showrefalways':       'always',
        'showrefdefault':      'mouseover',
        'showrefnever':        'never',
        'sort':                'Sort',
        'sortdate':            'by time (ascending)',
        'sortdatereverse':     'by time (descending)',
        'sorttitle':           'by title',
        'version_from':        'Version vom',
        'zones':               'Zones',

        'add_semtag':          'Add Semantic Tag',
        'add_tag':             'Add Simple Tag',
        'delete_semtag':       'Delete Semantic Tag',
        'delete_tag':          'Delete Simple Tag',
        'semtag':              'Semantic Tag',
        'semtags':             'Semantic Tags',
        'tag':                 'Simple Tag',
        'tags':                'Simple Tags',

        'delete_anno':         'Delete',
        'confirm_delete':      'Are you sure you want to delete this annotation?',

        'unsaved':             'Unsaved',
        'discard':             'Discard',
        'annoeditor':          'Annotation editor',

        "preview":             'Preview',

        "fmt_bold": "Bold",
    }
};

C.langcode = {
   'en':  'en',
   'eng': 'en',
   'de':  'de',
   'ger': 'de',
};
